// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as utilities from "../utilities";

// Export members:
export { GetSystemStatusResult } from "./getSystemStatus";
export const getSystemStatus: typeof import("./getSystemStatus").getSystemStatus = null as any;
utilities.lazyLoad(exports, ["getSystemStatus"], () => require("./getSystemStatus"));

