// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { GetNotificationArgs, GetNotificationResult, GetNotificationOutputArgs } from "./getNotification";
export const getNotification: typeof import("./getNotification").getNotification = null as any;
export const getNotificationOutput: typeof import("./getNotification").getNotificationOutput = null as any;
utilities.lazyLoad(exports, ["getNotification","getNotificationOutput"], () => require("./getNotification"));

export { GetNotificationsResult } from "./getNotifications";
export const getNotifications: typeof import("./getNotifications").getNotifications = null as any;
utilities.lazyLoad(exports, ["getNotifications"], () => require("./getNotifications"));

export { NotificationArgs, NotificationState } from "./notification";
export type Notification = import("./notification").Notification;
export const Notification: typeof import("./notification").Notification = null as any;
utilities.lazyLoad(exports, ["Notification"], () => require("./notification"));

export { NotificationBoxcarArgs, NotificationBoxcarState } from "./notificationBoxcar";
export type NotificationBoxcar = import("./notificationBoxcar").NotificationBoxcar;
export const NotificationBoxcar: typeof import("./notificationBoxcar").NotificationBoxcar = null as any;
utilities.lazyLoad(exports, ["NotificationBoxcar"], () => require("./notificationBoxcar"));

export { NotificationCustomScriptArgs, NotificationCustomScriptState } from "./notificationCustomScript";
export type NotificationCustomScript = import("./notificationCustomScript").NotificationCustomScript;
export const NotificationCustomScript: typeof import("./notificationCustomScript").NotificationCustomScript = null as any;
utilities.lazyLoad(exports, ["NotificationCustomScript"], () => require("./notificationCustomScript"));

export { NotificationDiscordArgs, NotificationDiscordState } from "./notificationDiscord";
export type NotificationDiscord = import("./notificationDiscord").NotificationDiscord;
export const NotificationDiscord: typeof import("./notificationDiscord").NotificationDiscord = null as any;
utilities.lazyLoad(exports, ["NotificationDiscord"], () => require("./notificationDiscord"));

export { NotificationEmailArgs, NotificationEmailState } from "./notificationEmail";
export type NotificationEmail = import("./notificationEmail").NotificationEmail;
export const NotificationEmail: typeof import("./notificationEmail").NotificationEmail = null as any;
utilities.lazyLoad(exports, ["NotificationEmail"], () => require("./notificationEmail"));

export { NotificationEmbyArgs, NotificationEmbyState } from "./notificationEmby";
export type NotificationEmby = import("./notificationEmby").NotificationEmby;
export const NotificationEmby: typeof import("./notificationEmby").NotificationEmby = null as any;
utilities.lazyLoad(exports, ["NotificationEmby"], () => require("./notificationEmby"));

export { NotificationGotifyArgs, NotificationGotifyState } from "./notificationGotify";
export type NotificationGotify = import("./notificationGotify").NotificationGotify;
export const NotificationGotify: typeof import("./notificationGotify").NotificationGotify = null as any;
utilities.lazyLoad(exports, ["NotificationGotify"], () => require("./notificationGotify"));

export { NotificationJoinArgs, NotificationJoinState } from "./notificationJoin";
export type NotificationJoin = import("./notificationJoin").NotificationJoin;
export const NotificationJoin: typeof import("./notificationJoin").NotificationJoin = null as any;
utilities.lazyLoad(exports, ["NotificationJoin"], () => require("./notificationJoin"));

export { NotificationKodiArgs, NotificationKodiState } from "./notificationKodi";
export type NotificationKodi = import("./notificationKodi").NotificationKodi;
export const NotificationKodi: typeof import("./notificationKodi").NotificationKodi = null as any;
utilities.lazyLoad(exports, ["NotificationKodi"], () => require("./notificationKodi"));

export { NotificationMailgunArgs, NotificationMailgunState } from "./notificationMailgun";
export type NotificationMailgun = import("./notificationMailgun").NotificationMailgun;
export const NotificationMailgun: typeof import("./notificationMailgun").NotificationMailgun = null as any;
utilities.lazyLoad(exports, ["NotificationMailgun"], () => require("./notificationMailgun"));

export { NotificationNotifiarrArgs, NotificationNotifiarrState } from "./notificationNotifiarr";
export type NotificationNotifiarr = import("./notificationNotifiarr").NotificationNotifiarr;
export const NotificationNotifiarr: typeof import("./notificationNotifiarr").NotificationNotifiarr = null as any;
utilities.lazyLoad(exports, ["NotificationNotifiarr"], () => require("./notificationNotifiarr"));

export { NotificationPlexArgs, NotificationPlexState } from "./notificationPlex";
export type NotificationPlex = import("./notificationPlex").NotificationPlex;
export const NotificationPlex: typeof import("./notificationPlex").NotificationPlex = null as any;
utilities.lazyLoad(exports, ["NotificationPlex"], () => require("./notificationPlex"));

export { NotificationProwlArgs, NotificationProwlState } from "./notificationProwl";
export type NotificationProwl = import("./notificationProwl").NotificationProwl;
export const NotificationProwl: typeof import("./notificationProwl").NotificationProwl = null as any;
utilities.lazyLoad(exports, ["NotificationProwl"], () => require("./notificationProwl"));

export { NotificationPushbulletArgs, NotificationPushbulletState } from "./notificationPushbullet";
export type NotificationPushbullet = import("./notificationPushbullet").NotificationPushbullet;
export const NotificationPushbullet: typeof import("./notificationPushbullet").NotificationPushbullet = null as any;
utilities.lazyLoad(exports, ["NotificationPushbullet"], () => require("./notificationPushbullet"));

export { NotificationPushoverArgs, NotificationPushoverState } from "./notificationPushover";
export type NotificationPushover = import("./notificationPushover").NotificationPushover;
export const NotificationPushover: typeof import("./notificationPushover").NotificationPushover = null as any;
utilities.lazyLoad(exports, ["NotificationPushover"], () => require("./notificationPushover"));

export { NotificationSendgridArgs, NotificationSendgridState } from "./notificationSendgrid";
export type NotificationSendgrid = import("./notificationSendgrid").NotificationSendgrid;
export const NotificationSendgrid: typeof import("./notificationSendgrid").NotificationSendgrid = null as any;
utilities.lazyLoad(exports, ["NotificationSendgrid"], () => require("./notificationSendgrid"));

export { NotificationSimplepushArgs, NotificationSimplepushState } from "./notificationSimplepush";
export type NotificationSimplepush = import("./notificationSimplepush").NotificationSimplepush;
export const NotificationSimplepush: typeof import("./notificationSimplepush").NotificationSimplepush = null as any;
utilities.lazyLoad(exports, ["NotificationSimplepush"], () => require("./notificationSimplepush"));

export { NotificationSlackArgs, NotificationSlackState } from "./notificationSlack";
export type NotificationSlack = import("./notificationSlack").NotificationSlack;
export const NotificationSlack: typeof import("./notificationSlack").NotificationSlack = null as any;
utilities.lazyLoad(exports, ["NotificationSlack"], () => require("./notificationSlack"));

export { NotificationSynologyIndexerArgs, NotificationSynologyIndexerState } from "./notificationSynologyIndexer";
export type NotificationSynologyIndexer = import("./notificationSynologyIndexer").NotificationSynologyIndexer;
export const NotificationSynologyIndexer: typeof import("./notificationSynologyIndexer").NotificationSynologyIndexer = null as any;
utilities.lazyLoad(exports, ["NotificationSynologyIndexer"], () => require("./notificationSynologyIndexer"));

export { NotificationTelegramArgs, NotificationTelegramState } from "./notificationTelegram";
export type NotificationTelegram = import("./notificationTelegram").NotificationTelegram;
export const NotificationTelegram: typeof import("./notificationTelegram").NotificationTelegram = null as any;
utilities.lazyLoad(exports, ["NotificationTelegram"], () => require("./notificationTelegram"));

export { NotificationTraktArgs, NotificationTraktState } from "./notificationTrakt";
export type NotificationTrakt = import("./notificationTrakt").NotificationTrakt;
export const NotificationTrakt: typeof import("./notificationTrakt").NotificationTrakt = null as any;
utilities.lazyLoad(exports, ["NotificationTrakt"], () => require("./notificationTrakt"));

export { NotificationTwitterArgs, NotificationTwitterState } from "./notificationTwitter";
export type NotificationTwitter = import("./notificationTwitter").NotificationTwitter;
export const NotificationTwitter: typeof import("./notificationTwitter").NotificationTwitter = null as any;
utilities.lazyLoad(exports, ["NotificationTwitter"], () => require("./notificationTwitter"));

export { NotificationWebhookArgs, NotificationWebhookState } from "./notificationWebhook";
export type NotificationWebhook = import("./notificationWebhook").NotificationWebhook;
export const NotificationWebhook: typeof import("./notificationWebhook").NotificationWebhook = null as any;
utilities.lazyLoad(exports, ["NotificationWebhook"], () => require("./notificationWebhook"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "whisparr:Notifications/notification:Notification":
                return new Notification(name, <any>undefined, { urn })
            case "whisparr:Notifications/notificationBoxcar:NotificationBoxcar":
                return new NotificationBoxcar(name, <any>undefined, { urn })
            case "whisparr:Notifications/notificationCustomScript:NotificationCustomScript":
                return new NotificationCustomScript(name, <any>undefined, { urn })
            case "whisparr:Notifications/notificationDiscord:NotificationDiscord":
                return new NotificationDiscord(name, <any>undefined, { urn })
            case "whisparr:Notifications/notificationEmail:NotificationEmail":
                return new NotificationEmail(name, <any>undefined, { urn })
            case "whisparr:Notifications/notificationEmby:NotificationEmby":
                return new NotificationEmby(name, <any>undefined, { urn })
            case "whisparr:Notifications/notificationGotify:NotificationGotify":
                return new NotificationGotify(name, <any>undefined, { urn })
            case "whisparr:Notifications/notificationJoin:NotificationJoin":
                return new NotificationJoin(name, <any>undefined, { urn })
            case "whisparr:Notifications/notificationKodi:NotificationKodi":
                return new NotificationKodi(name, <any>undefined, { urn })
            case "whisparr:Notifications/notificationMailgun:NotificationMailgun":
                return new NotificationMailgun(name, <any>undefined, { urn })
            case "whisparr:Notifications/notificationNotifiarr:NotificationNotifiarr":
                return new NotificationNotifiarr(name, <any>undefined, { urn })
            case "whisparr:Notifications/notificationPlex:NotificationPlex":
                return new NotificationPlex(name, <any>undefined, { urn })
            case "whisparr:Notifications/notificationProwl:NotificationProwl":
                return new NotificationProwl(name, <any>undefined, { urn })
            case "whisparr:Notifications/notificationPushbullet:NotificationPushbullet":
                return new NotificationPushbullet(name, <any>undefined, { urn })
            case "whisparr:Notifications/notificationPushover:NotificationPushover":
                return new NotificationPushover(name, <any>undefined, { urn })
            case "whisparr:Notifications/notificationSendgrid:NotificationSendgrid":
                return new NotificationSendgrid(name, <any>undefined, { urn })
            case "whisparr:Notifications/notificationSimplepush:NotificationSimplepush":
                return new NotificationSimplepush(name, <any>undefined, { urn })
            case "whisparr:Notifications/notificationSlack:NotificationSlack":
                return new NotificationSlack(name, <any>undefined, { urn })
            case "whisparr:Notifications/notificationSynologyIndexer:NotificationSynologyIndexer":
                return new NotificationSynologyIndexer(name, <any>undefined, { urn })
            case "whisparr:Notifications/notificationTelegram:NotificationTelegram":
                return new NotificationTelegram(name, <any>undefined, { urn })
            case "whisparr:Notifications/notificationTrakt:NotificationTrakt":
                return new NotificationTrakt(name, <any>undefined, { urn })
            case "whisparr:Notifications/notificationTwitter:NotificationTwitter":
                return new NotificationTwitter(name, <any>undefined, { urn })
            case "whisparr:Notifications/notificationWebhook:NotificationWebhook":
                return new NotificationWebhook(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("whisparr", "Notifications/notification", _module)
pulumi.runtime.registerResourceModule("whisparr", "Notifications/notificationBoxcar", _module)
pulumi.runtime.registerResourceModule("whisparr", "Notifications/notificationCustomScript", _module)
pulumi.runtime.registerResourceModule("whisparr", "Notifications/notificationDiscord", _module)
pulumi.runtime.registerResourceModule("whisparr", "Notifications/notificationEmail", _module)
pulumi.runtime.registerResourceModule("whisparr", "Notifications/notificationEmby", _module)
pulumi.runtime.registerResourceModule("whisparr", "Notifications/notificationGotify", _module)
pulumi.runtime.registerResourceModule("whisparr", "Notifications/notificationJoin", _module)
pulumi.runtime.registerResourceModule("whisparr", "Notifications/notificationKodi", _module)
pulumi.runtime.registerResourceModule("whisparr", "Notifications/notificationMailgun", _module)
pulumi.runtime.registerResourceModule("whisparr", "Notifications/notificationNotifiarr", _module)
pulumi.runtime.registerResourceModule("whisparr", "Notifications/notificationPlex", _module)
pulumi.runtime.registerResourceModule("whisparr", "Notifications/notificationProwl", _module)
pulumi.runtime.registerResourceModule("whisparr", "Notifications/notificationPushbullet", _module)
pulumi.runtime.registerResourceModule("whisparr", "Notifications/notificationPushover", _module)
pulumi.runtime.registerResourceModule("whisparr", "Notifications/notificationSendgrid", _module)
pulumi.runtime.registerResourceModule("whisparr", "Notifications/notificationSimplepush", _module)
pulumi.runtime.registerResourceModule("whisparr", "Notifications/notificationSlack", _module)
pulumi.runtime.registerResourceModule("whisparr", "Notifications/notificationSynologyIndexer", _module)
pulumi.runtime.registerResourceModule("whisparr", "Notifications/notificationTelegram", _module)
pulumi.runtime.registerResourceModule("whisparr", "Notifications/notificationTrakt", _module)
pulumi.runtime.registerResourceModule("whisparr", "Notifications/notificationTwitter", _module)
pulumi.runtime.registerResourceModule("whisparr", "Notifications/notificationWebhook", _module)
