// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Profiles -> Custom Format Condition Indexer Flag data source.
 * For more information refer to [Custom Format Conditions](https://wiki.servarr.com/whisparr/settings#conditions) and [Indexer Flag](https://wiki.servarr.com/whisparr/settings#indexer-flags).
 *
 * {{% examples %}}
 * ## Example Usage
 * {{% example %}}
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as whisparr from "@maienm/pulumi-whisparr";
 * import * as whisparr from "@pulumi/whisparr";
 *
 * const exampleCustomFormatConditionIndexerFlag = whisparr.Profiles.getCustomFormatConditionIndexerFlag({
 *     name: "AHD_UserRelease",
 *     negate: false,
 *     required: false,
 *     value: "1024",
 * });
 * const exampleCustomFormat = new whisparr.profiles.CustomFormat("exampleCustomFormat", {
 *     includeCustomFormatWhenRenaming: false,
 *     name: "Example",
 *     specifications: [exampleCustomFormatConditionIndexerFlag],
 * });
 * ```
 * {{% /example %}}
 * {{% /examples %}}
 */
export function getCustomFormatConditionIndexerFlag(args: GetCustomFormatConditionIndexerFlagArgs, opts?: pulumi.InvokeOptions): Promise<GetCustomFormatConditionIndexerFlagResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("whisparr:Profiles/getCustomFormatConditionIndexerFlag:getCustomFormatConditionIndexerFlag", {
        "name": args.name,
        "negate": args.negate,
        "required": args.required,
        "value": args.value,
    }, opts);
}

/**
 * A collection of arguments for invoking getCustomFormatConditionIndexerFlag.
 */
export interface GetCustomFormatConditionIndexerFlagArgs {
    /**
     * Specification name.
     */
    name: string;
    /**
     * Negate flag.
     */
    negate: boolean;
    /**
     * Computed flag.
     */
    required: boolean;
    /**
     * Indexer flag ID. `1` G Freeleech, `2` G Halfleech, `4` G DoubleUpload, `8` PTP Golden, `16` PTP Approved, `32` HDB Internal, `64` AHD Internal, `128` G Scene, `256` G Freeleech75, `512` G Freeleech25, `1024` AHD UserRelease.
     */
    value: string;
}

/**
 * A collection of values returned by getCustomFormatConditionIndexerFlag.
 */
export interface GetCustomFormatConditionIndexerFlagResult {
    /**
     * Custom format condition indexer flag ID.
     */
    readonly id: number;
    /**
     * Implementation.
     */
    readonly implementation: string;
    /**
     * Specification name.
     */
    readonly name: string;
    /**
     * Negate flag.
     */
    readonly negate: boolean;
    /**
     * Computed flag.
     */
    readonly required: boolean;
    /**
     * Indexer flag ID. `1` G Freeleech, `2` G Halfleech, `4` G DoubleUpload, `8` PTP Golden, `16` PTP Approved, `32` HDB Internal, `64` AHD Internal, `128` G Scene, `256` G Freeleech75, `512` G Freeleech25, `1024` AHD UserRelease.
     */
    readonly value: string;
}
/**
 * <!-- subcategory:Profiles -> Custom Format Condition Indexer Flag data source.
 * For more information refer to [Custom Format Conditions](https://wiki.servarr.com/whisparr/settings#conditions) and [Indexer Flag](https://wiki.servarr.com/whisparr/settings#indexer-flags).
 *
 * {{% examples %}}
 * ## Example Usage
 * {{% example %}}
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as whisparr from "@maienm/pulumi-whisparr";
 * import * as whisparr from "@pulumi/whisparr";
 *
 * const exampleCustomFormatConditionIndexerFlag = whisparr.Profiles.getCustomFormatConditionIndexerFlag({
 *     name: "AHD_UserRelease",
 *     negate: false,
 *     required: false,
 *     value: "1024",
 * });
 * const exampleCustomFormat = new whisparr.profiles.CustomFormat("exampleCustomFormat", {
 *     includeCustomFormatWhenRenaming: false,
 *     name: "Example",
 *     specifications: [exampleCustomFormatConditionIndexerFlag],
 * });
 * ```
 * {{% /example %}}
 * {{% /examples %}}
 */
export function getCustomFormatConditionIndexerFlagOutput(args: GetCustomFormatConditionIndexerFlagOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetCustomFormatConditionIndexerFlagResult> {
    return pulumi.output(args).apply((a: any) => getCustomFormatConditionIndexerFlag(a, opts))
}

/**
 * A collection of arguments for invoking getCustomFormatConditionIndexerFlag.
 */
export interface GetCustomFormatConditionIndexerFlagOutputArgs {
    /**
     * Specification name.
     */
    name: pulumi.Input<string>;
    /**
     * Negate flag.
     */
    negate: pulumi.Input<boolean>;
    /**
     * Computed flag.
     */
    required: pulumi.Input<boolean>;
    /**
     * Indexer flag ID. `1` G Freeleech, `2` G Halfleech, `4` G DoubleUpload, `8` PTP Golden, `16` PTP Approved, `32` HDB Internal, `64` AHD Internal, `128` G Scene, `256` G Freeleech75, `512` G Freeleech25, `1024` AHD UserRelease.
     */
    value: pulumi.Input<string>;
}
