// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { CustomFormatArgs, CustomFormatState } from "./customFormat";
export type CustomFormat = import("./customFormat").CustomFormat;
export const CustomFormat: typeof import("./customFormat").CustomFormat = null as any;
utilities.lazyLoad(exports, ["CustomFormat"], () => require("./customFormat"));

export { DelayProfileArgs, DelayProfileState } from "./delayProfile";
export type DelayProfile = import("./delayProfile").DelayProfile;
export const DelayProfile: typeof import("./delayProfile").DelayProfile = null as any;
utilities.lazyLoad(exports, ["DelayProfile"], () => require("./delayProfile"));

export { GetCustomFormatArgs, GetCustomFormatResult, GetCustomFormatOutputArgs } from "./getCustomFormat";
export const getCustomFormat: typeof import("./getCustomFormat").getCustomFormat = null as any;
export const getCustomFormatOutput: typeof import("./getCustomFormat").getCustomFormatOutput = null as any;
utilities.lazyLoad(exports, ["getCustomFormat","getCustomFormatOutput"], () => require("./getCustomFormat"));

export { GetCustomFormatConditionArgs, GetCustomFormatConditionResult, GetCustomFormatConditionOutputArgs } from "./getCustomFormatCondition";
export const getCustomFormatCondition: typeof import("./getCustomFormatCondition").getCustomFormatCondition = null as any;
export const getCustomFormatConditionOutput: typeof import("./getCustomFormatCondition").getCustomFormatConditionOutput = null as any;
utilities.lazyLoad(exports, ["getCustomFormatCondition","getCustomFormatConditionOutput"], () => require("./getCustomFormatCondition"));

export { GetCustomFormatConditionEditionArgs, GetCustomFormatConditionEditionResult, GetCustomFormatConditionEditionOutputArgs } from "./getCustomFormatConditionEdition";
export const getCustomFormatConditionEdition: typeof import("./getCustomFormatConditionEdition").getCustomFormatConditionEdition = null as any;
export const getCustomFormatConditionEditionOutput: typeof import("./getCustomFormatConditionEdition").getCustomFormatConditionEditionOutput = null as any;
utilities.lazyLoad(exports, ["getCustomFormatConditionEdition","getCustomFormatConditionEditionOutput"], () => require("./getCustomFormatConditionEdition"));

export { GetCustomFormatConditionIndexerFlagArgs, GetCustomFormatConditionIndexerFlagResult, GetCustomFormatConditionIndexerFlagOutputArgs } from "./getCustomFormatConditionIndexerFlag";
export const getCustomFormatConditionIndexerFlag: typeof import("./getCustomFormatConditionIndexerFlag").getCustomFormatConditionIndexerFlag = null as any;
export const getCustomFormatConditionIndexerFlagOutput: typeof import("./getCustomFormatConditionIndexerFlag").getCustomFormatConditionIndexerFlagOutput = null as any;
utilities.lazyLoad(exports, ["getCustomFormatConditionIndexerFlag","getCustomFormatConditionIndexerFlagOutput"], () => require("./getCustomFormatConditionIndexerFlag"));

export { GetCustomFormatConditionLanguageArgs, GetCustomFormatConditionLanguageResult, GetCustomFormatConditionLanguageOutputArgs } from "./getCustomFormatConditionLanguage";
export const getCustomFormatConditionLanguage: typeof import("./getCustomFormatConditionLanguage").getCustomFormatConditionLanguage = null as any;
export const getCustomFormatConditionLanguageOutput: typeof import("./getCustomFormatConditionLanguage").getCustomFormatConditionLanguageOutput = null as any;
utilities.lazyLoad(exports, ["getCustomFormatConditionLanguage","getCustomFormatConditionLanguageOutput"], () => require("./getCustomFormatConditionLanguage"));

export { GetCustomFormatConditionQualityModifierArgs, GetCustomFormatConditionQualityModifierResult, GetCustomFormatConditionQualityModifierOutputArgs } from "./getCustomFormatConditionQualityModifier";
export const getCustomFormatConditionQualityModifier: typeof import("./getCustomFormatConditionQualityModifier").getCustomFormatConditionQualityModifier = null as any;
export const getCustomFormatConditionQualityModifierOutput: typeof import("./getCustomFormatConditionQualityModifier").getCustomFormatConditionQualityModifierOutput = null as any;
utilities.lazyLoad(exports, ["getCustomFormatConditionQualityModifier","getCustomFormatConditionQualityModifierOutput"], () => require("./getCustomFormatConditionQualityModifier"));

export { GetCustomFormatConditionReleaseTitleArgs, GetCustomFormatConditionReleaseTitleResult, GetCustomFormatConditionReleaseTitleOutputArgs } from "./getCustomFormatConditionReleaseTitle";
export const getCustomFormatConditionReleaseTitle: typeof import("./getCustomFormatConditionReleaseTitle").getCustomFormatConditionReleaseTitle = null as any;
export const getCustomFormatConditionReleaseTitleOutput: typeof import("./getCustomFormatConditionReleaseTitle").getCustomFormatConditionReleaseTitleOutput = null as any;
utilities.lazyLoad(exports, ["getCustomFormatConditionReleaseTitle","getCustomFormatConditionReleaseTitleOutput"], () => require("./getCustomFormatConditionReleaseTitle"));

export { GetCustomFormatConditionResolutionArgs, GetCustomFormatConditionResolutionResult, GetCustomFormatConditionResolutionOutputArgs } from "./getCustomFormatConditionResolution";
export const getCustomFormatConditionResolution: typeof import("./getCustomFormatConditionResolution").getCustomFormatConditionResolution = null as any;
export const getCustomFormatConditionResolutionOutput: typeof import("./getCustomFormatConditionResolution").getCustomFormatConditionResolutionOutput = null as any;
utilities.lazyLoad(exports, ["getCustomFormatConditionResolution","getCustomFormatConditionResolutionOutput"], () => require("./getCustomFormatConditionResolution"));

export { GetCustomFormatConditionSizeArgs, GetCustomFormatConditionSizeResult, GetCustomFormatConditionSizeOutputArgs } from "./getCustomFormatConditionSize";
export const getCustomFormatConditionSize: typeof import("./getCustomFormatConditionSize").getCustomFormatConditionSize = null as any;
export const getCustomFormatConditionSizeOutput: typeof import("./getCustomFormatConditionSize").getCustomFormatConditionSizeOutput = null as any;
utilities.lazyLoad(exports, ["getCustomFormatConditionSize","getCustomFormatConditionSizeOutput"], () => require("./getCustomFormatConditionSize"));

export { GetCustomFormatConditionSourceArgs, GetCustomFormatConditionSourceResult, GetCustomFormatConditionSourceOutputArgs } from "./getCustomFormatConditionSource";
export const getCustomFormatConditionSource: typeof import("./getCustomFormatConditionSource").getCustomFormatConditionSource = null as any;
export const getCustomFormatConditionSourceOutput: typeof import("./getCustomFormatConditionSource").getCustomFormatConditionSourceOutput = null as any;
utilities.lazyLoad(exports, ["getCustomFormatConditionSource","getCustomFormatConditionSourceOutput"], () => require("./getCustomFormatConditionSource"));

export { GetCustomFormatsResult } from "./getCustomFormats";
export const getCustomFormats: typeof import("./getCustomFormats").getCustomFormats = null as any;
utilities.lazyLoad(exports, ["getCustomFormats"], () => require("./getCustomFormats"));

export { GetDelayProfileArgs, GetDelayProfileResult, GetDelayProfileOutputArgs } from "./getDelayProfile";
export const getDelayProfile: typeof import("./getDelayProfile").getDelayProfile = null as any;
export const getDelayProfileOutput: typeof import("./getDelayProfile").getDelayProfileOutput = null as any;
utilities.lazyLoad(exports, ["getDelayProfile","getDelayProfileOutput"], () => require("./getDelayProfile"));

export { GetDelayProfilesResult } from "./getDelayProfiles";
export const getDelayProfiles: typeof import("./getDelayProfiles").getDelayProfiles = null as any;
utilities.lazyLoad(exports, ["getDelayProfiles"], () => require("./getDelayProfiles"));

export { GetQualityArgs, GetQualityResult, GetQualityOutputArgs } from "./getQuality";
export const getQuality: typeof import("./getQuality").getQuality = null as any;
export const getQualityOutput: typeof import("./getQuality").getQualityOutput = null as any;
utilities.lazyLoad(exports, ["getQuality","getQualityOutput"], () => require("./getQuality"));

export { GetQualityDefinitionArgs, GetQualityDefinitionResult, GetQualityDefinitionOutputArgs } from "./getQualityDefinition";
export const getQualityDefinition: typeof import("./getQualityDefinition").getQualityDefinition = null as any;
export const getQualityDefinitionOutput: typeof import("./getQualityDefinition").getQualityDefinitionOutput = null as any;
utilities.lazyLoad(exports, ["getQualityDefinition","getQualityDefinitionOutput"], () => require("./getQualityDefinition"));

export { GetQualityDefinitionsResult } from "./getQualityDefinitions";
export const getQualityDefinitions: typeof import("./getQualityDefinitions").getQualityDefinitions = null as any;
utilities.lazyLoad(exports, ["getQualityDefinitions"], () => require("./getQualityDefinitions"));

export { GetQualityProfileArgs, GetQualityProfileResult, GetQualityProfileOutputArgs } from "./getQualityProfile";
export const getQualityProfile: typeof import("./getQualityProfile").getQualityProfile = null as any;
export const getQualityProfileOutput: typeof import("./getQualityProfile").getQualityProfileOutput = null as any;
utilities.lazyLoad(exports, ["getQualityProfile","getQualityProfileOutput"], () => require("./getQualityProfile"));

export { GetQualityProfilesResult } from "./getQualityProfiles";
export const getQualityProfiles: typeof import("./getQualityProfiles").getQualityProfiles = null as any;
utilities.lazyLoad(exports, ["getQualityProfiles"], () => require("./getQualityProfiles"));

export { QualityDefinitionArgs, QualityDefinitionState } from "./qualityDefinition";
export type QualityDefinition = import("./qualityDefinition").QualityDefinition;
export const QualityDefinition: typeof import("./qualityDefinition").QualityDefinition = null as any;
utilities.lazyLoad(exports, ["QualityDefinition"], () => require("./qualityDefinition"));

export { QualityProfileArgs, QualityProfileState } from "./qualityProfile";
export type QualityProfile = import("./qualityProfile").QualityProfile;
export const QualityProfile: typeof import("./qualityProfile").QualityProfile = null as any;
utilities.lazyLoad(exports, ["QualityProfile"], () => require("./qualityProfile"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "whisparr:Profiles/customFormat:CustomFormat":
                return new CustomFormat(name, <any>undefined, { urn })
            case "whisparr:Profiles/delayProfile:DelayProfile":
                return new DelayProfile(name, <any>undefined, { urn })
            case "whisparr:Profiles/qualityDefinition:QualityDefinition":
                return new QualityDefinition(name, <any>undefined, { urn })
            case "whisparr:Profiles/qualityProfile:QualityProfile":
                return new QualityProfile(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("whisparr", "Profiles/customFormat", _module)
pulumi.runtime.registerResourceModule("whisparr", "Profiles/delayProfile", _module)
pulumi.runtime.registerResourceModule("whisparr", "Profiles/qualityDefinition", _module)
pulumi.runtime.registerResourceModule("whisparr", "Profiles/qualityProfile", _module)
