// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Media Management -->Single Root Folder.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as whisparr from "@pulumi/whisparr";
 *
 * const example = whisparr.MediaManagement.getRootFolder({
 *     path: "/example",
 * });
 * ```
 */
export function getRootFolder(args: GetRootFolderArgs, opts?: pulumi.InvokeOptions): Promise<GetRootFolderResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("whisparr:MediaManagement/getRootFolder:getRootFolder", {
        "path": args.path,
    }, opts);
}

/**
 * A collection of arguments for invoking getRootFolder.
 */
export interface GetRootFolderArgs {
    /**
     * Root Folder absolute path.
     */
    path: string;
}

/**
 * A collection of values returned by getRootFolder.
 */
export interface GetRootFolderResult {
    /**
     * Access flag.
     */
    readonly accessible: boolean;
    /**
     * Root Folder ID.
     */
    readonly id: number;
    /**
     * Root Folder absolute path.
     */
    readonly path: string;
    /**
     * List of folders with no associated series.
     */
    readonly unmappedFolders: outputs.MediaManagement.GetRootFolderUnmappedFolder[];
}
/**
 * <!-- subcategory:Media Management -->Single Root Folder.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as whisparr from "@pulumi/whisparr";
 *
 * const example = whisparr.MediaManagement.getRootFolder({
 *     path: "/example",
 * });
 * ```
 */
export function getRootFolderOutput(args: GetRootFolderOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetRootFolderResult> {
    return pulumi.output(args).apply((a: any) => getRootFolder(a, opts))
}

/**
 * A collection of arguments for invoking getRootFolder.
 */
export interface GetRootFolderOutputArgs {
    /**
     * Root Folder absolute path.
     */
    path: pulumi.Input<string>;
}
