// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Media Management -->Naming resource.
 * For more information refer to [Naming](https://wiki.servarr.com/whisparr/settings#community-naming-suggestions) documentation.
 *
 * ## Import
 *
 * import does not need parameters
 *
 * ```sh
 *  $ pulumi import whisparr:MediaManagement/naming:Naming example
 * ```
 */
export class Naming extends pulumi.CustomResource {
    /**
     * Get an existing Naming resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NamingState, opts?: pulumi.CustomResourceOptions): Naming {
        return new Naming(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'whisparr:MediaManagement/naming:Naming';

    /**
     * Returns true if the given object is an instance of Naming.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Naming {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Naming.__pulumiType;
    }

    /**
     * Change how Whisparr handles colon replacement. Valid values are: 'delete', 'dash', 'spaceDash', and 'spaceDashSpace'.
     */
    public readonly colonReplacementFormat!: pulumi.Output<string>;
    /**
     * Include quality in file name.
     */
    public readonly includeQuality!: pulumi.Output<boolean>;
    /**
     * Movie folder format.
     */
    public readonly movieFolderFormat!: pulumi.Output<string>;
    /**
     * Whisparr will use the existing file name if false.
     */
    public readonly renameMovies!: pulumi.Output<boolean>;
    /**
     * Replace illegal characters. They will be removed if false.
     */
    public readonly replaceIllegalCharacters!: pulumi.Output<boolean>;
    /**
     * Replace spaces.
     */
    public readonly replaceSpaces!: pulumi.Output<boolean>;
    /**
     * Standard movie formatss.
     */
    public readonly standardMovieFormat!: pulumi.Output<string>;

    /**
     * Create a Naming resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NamingArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NamingArgs | NamingState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as NamingState | undefined;
            resourceInputs["colonReplacementFormat"] = state ? state.colonReplacementFormat : undefined;
            resourceInputs["includeQuality"] = state ? state.includeQuality : undefined;
            resourceInputs["movieFolderFormat"] = state ? state.movieFolderFormat : undefined;
            resourceInputs["renameMovies"] = state ? state.renameMovies : undefined;
            resourceInputs["replaceIllegalCharacters"] = state ? state.replaceIllegalCharacters : undefined;
            resourceInputs["replaceSpaces"] = state ? state.replaceSpaces : undefined;
            resourceInputs["standardMovieFormat"] = state ? state.standardMovieFormat : undefined;
        } else {
            const args = argsOrState as NamingArgs | undefined;
            if ((!args || args.colonReplacementFormat === undefined) && !opts.urn) {
                throw new Error("Missing required property 'colonReplacementFormat'");
            }
            if ((!args || args.includeQuality === undefined) && !opts.urn) {
                throw new Error("Missing required property 'includeQuality'");
            }
            if ((!args || args.movieFolderFormat === undefined) && !opts.urn) {
                throw new Error("Missing required property 'movieFolderFormat'");
            }
            if ((!args || args.renameMovies === undefined) && !opts.urn) {
                throw new Error("Missing required property 'renameMovies'");
            }
            if ((!args || args.replaceIllegalCharacters === undefined) && !opts.urn) {
                throw new Error("Missing required property 'replaceIllegalCharacters'");
            }
            if ((!args || args.replaceSpaces === undefined) && !opts.urn) {
                throw new Error("Missing required property 'replaceSpaces'");
            }
            if ((!args || args.standardMovieFormat === undefined) && !opts.urn) {
                throw new Error("Missing required property 'standardMovieFormat'");
            }
            resourceInputs["colonReplacementFormat"] = args ? args.colonReplacementFormat : undefined;
            resourceInputs["includeQuality"] = args ? args.includeQuality : undefined;
            resourceInputs["movieFolderFormat"] = args ? args.movieFolderFormat : undefined;
            resourceInputs["renameMovies"] = args ? args.renameMovies : undefined;
            resourceInputs["replaceIllegalCharacters"] = args ? args.replaceIllegalCharacters : undefined;
            resourceInputs["replaceSpaces"] = args ? args.replaceSpaces : undefined;
            resourceInputs["standardMovieFormat"] = args ? args.standardMovieFormat : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Naming.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Naming resources.
 */
export interface NamingState {
    /**
     * Change how Whisparr handles colon replacement. Valid values are: 'delete', 'dash', 'spaceDash', and 'spaceDashSpace'.
     */
    colonReplacementFormat?: pulumi.Input<string>;
    /**
     * Include quality in file name.
     */
    includeQuality?: pulumi.Input<boolean>;
    /**
     * Movie folder format.
     */
    movieFolderFormat?: pulumi.Input<string>;
    /**
     * Whisparr will use the existing file name if false.
     */
    renameMovies?: pulumi.Input<boolean>;
    /**
     * Replace illegal characters. They will be removed if false.
     */
    replaceIllegalCharacters?: pulumi.Input<boolean>;
    /**
     * Replace spaces.
     */
    replaceSpaces?: pulumi.Input<boolean>;
    /**
     * Standard movie formatss.
     */
    standardMovieFormat?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Naming resource.
 */
export interface NamingArgs {
    /**
     * Change how Whisparr handles colon replacement. Valid values are: 'delete', 'dash', 'spaceDash', and 'spaceDashSpace'.
     */
    colonReplacementFormat: pulumi.Input<string>;
    /**
     * Include quality in file name.
     */
    includeQuality: pulumi.Input<boolean>;
    /**
     * Movie folder format.
     */
    movieFolderFormat: pulumi.Input<string>;
    /**
     * Whisparr will use the existing file name if false.
     */
    renameMovies: pulumi.Input<boolean>;
    /**
     * Replace illegal characters. They will be removed if false.
     */
    replaceIllegalCharacters: pulumi.Input<boolean>;
    /**
     * Replace spaces.
     */
    replaceSpaces: pulumi.Input<boolean>;
    /**
     * Standard movie formatss.
     */
    standardMovieFormat: pulumi.Input<string>;
}
