// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Import Lists -->Import List TMDB Person resource.
 * For more information refer to [Import List](https://wiki.servarr.com/whisparr/settings#import-lists) and [TMDB Person](https://wiki.servarr.com/whisparr/supported#tmdbpersonimport).
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as whisparr from "@maienm/pulumi-whisparr";
 *
 * const example = new whisparr.importlists.ImportListTmdbPerson("example", {
 *     cast: true,
 *     castDirector: true,
 *     castProducer: true,
 *     castSound: true,
 *     castWriting: true,
 *     enableAuto: false,
 *     enabled: true,
 *     minimumAvailability: "tba",
 *     name: "Example",
 *     personId: "11842",
 *     qualityProfileId: 1,
 *     rootFolderPath: "/config",
 *     searchOnAdd: false,
 *     shouldMonitor: true,
 * });
 * ```
 *
 * ## Import
 *
 * import using the API/UI ID
 *
 * ```sh
 *  $ pulumi import whisparr:ImportLists/importListTmdbPerson:ImportListTmdbPerson example 1
 * ```
 */
export class ImportListTmdbPerson extends pulumi.CustomResource {
    /**
     * Get an existing ImportListTmdbPerson resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ImportListTmdbPersonState, opts?: pulumi.CustomResourceOptions): ImportListTmdbPerson {
        return new ImportListTmdbPerson(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'whisparr:ImportLists/importListTmdbPerson:ImportListTmdbPerson';

    /**
     * Returns true if the given object is an instance of ImportListTmdbPerson.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ImportListTmdbPerson {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ImportListTmdbPerson.__pulumiType;
    }

    /**
     * Include cast.
     */
    public readonly cast!: pulumi.Output<boolean>;
    /**
     * Include cast director.
     */
    public readonly castDirector!: pulumi.Output<boolean>;
    /**
     * Include cast producer.
     */
    public readonly castProducer!: pulumi.Output<boolean>;
    /**
     * Include cast sound.
     */
    public readonly castSound!: pulumi.Output<boolean>;
    /**
     * Include cast writing.
     */
    public readonly castWriting!: pulumi.Output<boolean>;
    /**
     * Enable automatic add flag.
     */
    public readonly enableAuto!: pulumi.Output<boolean>;
    /**
     * Enabled flag.
     */
    public readonly enabled!: pulumi.Output<boolean>;
    /**
     * List order.
     */
    public readonly listOrder!: pulumi.Output<number>;
    /**
     * Minimum availability.
     */
    public readonly minimumAvailability!: pulumi.Output<string>;
    /**
     * Import List name.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Person ID.
     */
    public readonly personId!: pulumi.Output<string>;
    /**
     * Quality profile ID.
     */
    public readonly qualityProfileId!: pulumi.Output<number>;
    /**
     * Root folder path.
     */
    public readonly rootFolderPath!: pulumi.Output<string>;
    /**
     * Search on add flag.
     */
    public readonly searchOnAdd!: pulumi.Output<boolean>;
    /**
     * Should monitor.
     */
    public readonly shouldMonitor!: pulumi.Output<boolean>;
    /**
     * List of associated tags.
     */
    public readonly tags!: pulumi.Output<number[]>;

    /**
     * Create a ImportListTmdbPerson resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ImportListTmdbPersonArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ImportListTmdbPersonArgs | ImportListTmdbPersonState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ImportListTmdbPersonState | undefined;
            resourceInputs["cast"] = state ? state.cast : undefined;
            resourceInputs["castDirector"] = state ? state.castDirector : undefined;
            resourceInputs["castProducer"] = state ? state.castProducer : undefined;
            resourceInputs["castSound"] = state ? state.castSound : undefined;
            resourceInputs["castWriting"] = state ? state.castWriting : undefined;
            resourceInputs["enableAuto"] = state ? state.enableAuto : undefined;
            resourceInputs["enabled"] = state ? state.enabled : undefined;
            resourceInputs["listOrder"] = state ? state.listOrder : undefined;
            resourceInputs["minimumAvailability"] = state ? state.minimumAvailability : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["personId"] = state ? state.personId : undefined;
            resourceInputs["qualityProfileId"] = state ? state.qualityProfileId : undefined;
            resourceInputs["rootFolderPath"] = state ? state.rootFolderPath : undefined;
            resourceInputs["searchOnAdd"] = state ? state.searchOnAdd : undefined;
            resourceInputs["shouldMonitor"] = state ? state.shouldMonitor : undefined;
            resourceInputs["tags"] = state ? state.tags : undefined;
        } else {
            const args = argsOrState as ImportListTmdbPersonArgs | undefined;
            if ((!args || args.minimumAvailability === undefined) && !opts.urn) {
                throw new Error("Missing required property 'minimumAvailability'");
            }
            if ((!args || args.name === undefined) && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if ((!args || args.personId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'personId'");
            }
            if ((!args || args.qualityProfileId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'qualityProfileId'");
            }
            if ((!args || args.rootFolderPath === undefined) && !opts.urn) {
                throw new Error("Missing required property 'rootFolderPath'");
            }
            if ((!args || args.shouldMonitor === undefined) && !opts.urn) {
                throw new Error("Missing required property 'shouldMonitor'");
            }
            resourceInputs["cast"] = args ? args.cast : undefined;
            resourceInputs["castDirector"] = args ? args.castDirector : undefined;
            resourceInputs["castProducer"] = args ? args.castProducer : undefined;
            resourceInputs["castSound"] = args ? args.castSound : undefined;
            resourceInputs["castWriting"] = args ? args.castWriting : undefined;
            resourceInputs["enableAuto"] = args ? args.enableAuto : undefined;
            resourceInputs["enabled"] = args ? args.enabled : undefined;
            resourceInputs["listOrder"] = args ? args.listOrder : undefined;
            resourceInputs["minimumAvailability"] = args ? args.minimumAvailability : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["personId"] = args ? args.personId : undefined;
            resourceInputs["qualityProfileId"] = args ? args.qualityProfileId : undefined;
            resourceInputs["rootFolderPath"] = args ? args.rootFolderPath : undefined;
            resourceInputs["searchOnAdd"] = args ? args.searchOnAdd : undefined;
            resourceInputs["shouldMonitor"] = args ? args.shouldMonitor : undefined;
            resourceInputs["tags"] = args ? args.tags : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ImportListTmdbPerson.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ImportListTmdbPerson resources.
 */
export interface ImportListTmdbPersonState {
    /**
     * Include cast.
     */
    cast?: pulumi.Input<boolean>;
    /**
     * Include cast director.
     */
    castDirector?: pulumi.Input<boolean>;
    /**
     * Include cast producer.
     */
    castProducer?: pulumi.Input<boolean>;
    /**
     * Include cast sound.
     */
    castSound?: pulumi.Input<boolean>;
    /**
     * Include cast writing.
     */
    castWriting?: pulumi.Input<boolean>;
    /**
     * Enable automatic add flag.
     */
    enableAuto?: pulumi.Input<boolean>;
    /**
     * Enabled flag.
     */
    enabled?: pulumi.Input<boolean>;
    /**
     * List order.
     */
    listOrder?: pulumi.Input<number>;
    /**
     * Minimum availability.
     */
    minimumAvailability?: pulumi.Input<string>;
    /**
     * Import List name.
     */
    name?: pulumi.Input<string>;
    /**
     * Person ID.
     */
    personId?: pulumi.Input<string>;
    /**
     * Quality profile ID.
     */
    qualityProfileId?: pulumi.Input<number>;
    /**
     * Root folder path.
     */
    rootFolderPath?: pulumi.Input<string>;
    /**
     * Search on add flag.
     */
    searchOnAdd?: pulumi.Input<boolean>;
    /**
     * Should monitor.
     */
    shouldMonitor?: pulumi.Input<boolean>;
    /**
     * List of associated tags.
     */
    tags?: pulumi.Input<pulumi.Input<number>[]>;
}

/**
 * The set of arguments for constructing a ImportListTmdbPerson resource.
 */
export interface ImportListTmdbPersonArgs {
    /**
     * Include cast.
     */
    cast?: pulumi.Input<boolean>;
    /**
     * Include cast director.
     */
    castDirector?: pulumi.Input<boolean>;
    /**
     * Include cast producer.
     */
    castProducer?: pulumi.Input<boolean>;
    /**
     * Include cast sound.
     */
    castSound?: pulumi.Input<boolean>;
    /**
     * Include cast writing.
     */
    castWriting?: pulumi.Input<boolean>;
    /**
     * Enable automatic add flag.
     */
    enableAuto?: pulumi.Input<boolean>;
    /**
     * Enabled flag.
     */
    enabled?: pulumi.Input<boolean>;
    /**
     * List order.
     */
    listOrder?: pulumi.Input<number>;
    /**
     * Minimum availability.
     */
    minimumAvailability: pulumi.Input<string>;
    /**
     * Import List name.
     */
    name: pulumi.Input<string>;
    /**
     * Person ID.
     */
    personId: pulumi.Input<string>;
    /**
     * Quality profile ID.
     */
    qualityProfileId: pulumi.Input<number>;
    /**
     * Root folder path.
     */
    rootFolderPath: pulumi.Input<string>;
    /**
     * Search on add flag.
     */
    searchOnAdd?: pulumi.Input<boolean>;
    /**
     * Should monitor.
     */
    shouldMonitor: pulumi.Input<boolean>;
    /**
     * List of associated tags.
     */
    tags?: pulumi.Input<pulumi.Input<number>[]>;
}
