// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Import Lists -->Import List Config resource.
 * For more information refer to [Import List](https://wiki.servarr.com/whisparr/settings#completed-download-handling) documentation.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as whisparr from "@maienm/pulumi-whisparr";
 *
 * const example = new whisparr.importlists.ImportListConfig("example", {
 *     syncInterval: 24,
 *     syncLevel: "logOnly",
 * });
 * ```
 *
 * ## Import
 *
 * import does not need parameters
 *
 * ```sh
 *  $ pulumi import whisparr:ImportLists/importListConfig:ImportListConfig example
 * ```
 */
export class ImportListConfig extends pulumi.CustomResource {
    /**
     * Get an existing ImportListConfig resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ImportListConfigState, opts?: pulumi.CustomResourceOptions): ImportListConfig {
        return new ImportListConfig(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'whisparr:ImportLists/importListConfig:ImportListConfig';

    /**
     * Returns true if the given object is an instance of ImportListConfig.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ImportListConfig {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ImportListConfig.__pulumiType;
    }

    /**
     * List Update Interval.
     */
    public readonly syncInterval!: pulumi.Output<number>;
    /**
     * Clean library level.
     */
    public readonly syncLevel!: pulumi.Output<string>;

    /**
     * Create a ImportListConfig resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ImportListConfigArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ImportListConfigArgs | ImportListConfigState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ImportListConfigState | undefined;
            resourceInputs["syncInterval"] = state ? state.syncInterval : undefined;
            resourceInputs["syncLevel"] = state ? state.syncLevel : undefined;
        } else {
            const args = argsOrState as ImportListConfigArgs | undefined;
            if ((!args || args.syncInterval === undefined) && !opts.urn) {
                throw new Error("Missing required property 'syncInterval'");
            }
            if ((!args || args.syncLevel === undefined) && !opts.urn) {
                throw new Error("Missing required property 'syncLevel'");
            }
            resourceInputs["syncInterval"] = args ? args.syncInterval : undefined;
            resourceInputs["syncLevel"] = args ? args.syncLevel : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ImportListConfig.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ImportListConfig resources.
 */
export interface ImportListConfigState {
    /**
     * List Update Interval.
     */
    syncInterval?: pulumi.Input<number>;
    /**
     * Clean library level.
     */
    syncLevel?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ImportListConfig resource.
 */
export interface ImportListConfigArgs {
    /**
     * List Update Interval.
     */
    syncInterval: pulumi.Input<number>;
    /**
     * Clean library level.
     */
    syncLevel: pulumi.Input<string>;
}
