// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { GetIndexerArgs, GetIndexerResult, GetIndexerOutputArgs } from "./getIndexer";
export const getIndexer: typeof import("./getIndexer").getIndexer = null as any;
export const getIndexerOutput: typeof import("./getIndexer").getIndexerOutput = null as any;
utilities.lazyLoad(exports, ["getIndexer","getIndexerOutput"], () => require("./getIndexer"));

export { GetIndexerConfigResult } from "./getIndexerConfig";
export const getIndexerConfig: typeof import("./getIndexerConfig").getIndexerConfig = null as any;
utilities.lazyLoad(exports, ["getIndexerConfig"], () => require("./getIndexerConfig"));

export { GetIndexersResult } from "./getIndexers";
export const getIndexers: typeof import("./getIndexers").getIndexers = null as any;
utilities.lazyLoad(exports, ["getIndexers"], () => require("./getIndexers"));

export { GetRestrictionArgs, GetRestrictionResult, GetRestrictionOutputArgs } from "./getRestriction";
export const getRestriction: typeof import("./getRestriction").getRestriction = null as any;
export const getRestrictionOutput: typeof import("./getRestriction").getRestrictionOutput = null as any;
utilities.lazyLoad(exports, ["getRestriction","getRestrictionOutput"], () => require("./getRestriction"));

export { GetRestrictionsResult } from "./getRestrictions";
export const getRestrictions: typeof import("./getRestrictions").getRestrictions = null as any;
utilities.lazyLoad(exports, ["getRestrictions"], () => require("./getRestrictions"));

export { IndexerArgs, IndexerState } from "./indexer";
export type Indexer = import("./indexer").Indexer;
export const Indexer: typeof import("./indexer").Indexer = null as any;
utilities.lazyLoad(exports, ["Indexer"], () => require("./indexer"));

export { IndexerConfigArgs, IndexerConfigState } from "./indexerConfig";
export type IndexerConfig = import("./indexerConfig").IndexerConfig;
export const IndexerConfig: typeof import("./indexerConfig").IndexerConfig = null as any;
utilities.lazyLoad(exports, ["IndexerConfig"], () => require("./indexerConfig"));

export { IndexerFilelistArgs, IndexerFilelistState } from "./indexerFilelist";
export type IndexerFilelist = import("./indexerFilelist").IndexerFilelist;
export const IndexerFilelist: typeof import("./indexerFilelist").IndexerFilelist = null as any;
utilities.lazyLoad(exports, ["IndexerFilelist"], () => require("./indexerFilelist"));

export { IndexerHdbitsArgs, IndexerHdbitsState } from "./indexerHdbits";
export type IndexerHdbits = import("./indexerHdbits").IndexerHdbits;
export const IndexerHdbits: typeof import("./indexerHdbits").IndexerHdbits = null as any;
utilities.lazyLoad(exports, ["IndexerHdbits"], () => require("./indexerHdbits"));

export { IndexerIptorrentsArgs, IndexerIptorrentsState } from "./indexerIptorrents";
export type IndexerIptorrents = import("./indexerIptorrents").IndexerIptorrents;
export const IndexerIptorrents: typeof import("./indexerIptorrents").IndexerIptorrents = null as any;
utilities.lazyLoad(exports, ["IndexerIptorrents"], () => require("./indexerIptorrents"));

export { IndexerNewznabArgs, IndexerNewznabState } from "./indexerNewznab";
export type IndexerNewznab = import("./indexerNewznab").IndexerNewznab;
export const IndexerNewznab: typeof import("./indexerNewznab").IndexerNewznab = null as any;
utilities.lazyLoad(exports, ["IndexerNewznab"], () => require("./indexerNewznab"));

export { IndexerNyaaArgs, IndexerNyaaState } from "./indexerNyaa";
export type IndexerNyaa = import("./indexerNyaa").IndexerNyaa;
export const IndexerNyaa: typeof import("./indexerNyaa").IndexerNyaa = null as any;
utilities.lazyLoad(exports, ["IndexerNyaa"], () => require("./indexerNyaa"));

export { IndexerOmgwtfnzbsArgs, IndexerOmgwtfnzbsState } from "./indexerOmgwtfnzbs";
export type IndexerOmgwtfnzbs = import("./indexerOmgwtfnzbs").IndexerOmgwtfnzbs;
export const IndexerOmgwtfnzbs: typeof import("./indexerOmgwtfnzbs").IndexerOmgwtfnzbs = null as any;
utilities.lazyLoad(exports, ["IndexerOmgwtfnzbs"], () => require("./indexerOmgwtfnzbs"));

export { IndexerRarbgArgs, IndexerRarbgState } from "./indexerRarbg";
export type IndexerRarbg = import("./indexerRarbg").IndexerRarbg;
export const IndexerRarbg: typeof import("./indexerRarbg").IndexerRarbg = null as any;
utilities.lazyLoad(exports, ["IndexerRarbg"], () => require("./indexerRarbg"));

export { IndexerTorrentPotatoArgs, IndexerTorrentPotatoState } from "./indexerTorrentPotato";
export type IndexerTorrentPotato = import("./indexerTorrentPotato").IndexerTorrentPotato;
export const IndexerTorrentPotato: typeof import("./indexerTorrentPotato").IndexerTorrentPotato = null as any;
utilities.lazyLoad(exports, ["IndexerTorrentPotato"], () => require("./indexerTorrentPotato"));

export { IndexerTorrentRssArgs, IndexerTorrentRssState } from "./indexerTorrentRss";
export type IndexerTorrentRss = import("./indexerTorrentRss").IndexerTorrentRss;
export const IndexerTorrentRss: typeof import("./indexerTorrentRss").IndexerTorrentRss = null as any;
utilities.lazyLoad(exports, ["IndexerTorrentRss"], () => require("./indexerTorrentRss"));

export { IndexerTorznabArgs, IndexerTorznabState } from "./indexerTorznab";
export type IndexerTorznab = import("./indexerTorznab").IndexerTorznab;
export const IndexerTorznab: typeof import("./indexerTorznab").IndexerTorznab = null as any;
utilities.lazyLoad(exports, ["IndexerTorznab"], () => require("./indexerTorznab"));

export { RestrictionArgs, RestrictionState } from "./restriction";
export type Restriction = import("./restriction").Restriction;
export const Restriction: typeof import("./restriction").Restriction = null as any;
utilities.lazyLoad(exports, ["Restriction"], () => require("./restriction"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "whisparr:Indexers/indexer:Indexer":
                return new Indexer(name, <any>undefined, { urn })
            case "whisparr:Indexers/indexerConfig:IndexerConfig":
                return new IndexerConfig(name, <any>undefined, { urn })
            case "whisparr:Indexers/indexerFilelist:IndexerFilelist":
                return new IndexerFilelist(name, <any>undefined, { urn })
            case "whisparr:Indexers/indexerHdbits:IndexerHdbits":
                return new IndexerHdbits(name, <any>undefined, { urn })
            case "whisparr:Indexers/indexerIptorrents:IndexerIptorrents":
                return new IndexerIptorrents(name, <any>undefined, { urn })
            case "whisparr:Indexers/indexerNewznab:IndexerNewznab":
                return new IndexerNewznab(name, <any>undefined, { urn })
            case "whisparr:Indexers/indexerNyaa:IndexerNyaa":
                return new IndexerNyaa(name, <any>undefined, { urn })
            case "whisparr:Indexers/indexerOmgwtfnzbs:IndexerOmgwtfnzbs":
                return new IndexerOmgwtfnzbs(name, <any>undefined, { urn })
            case "whisparr:Indexers/indexerRarbg:IndexerRarbg":
                return new IndexerRarbg(name, <any>undefined, { urn })
            case "whisparr:Indexers/indexerTorrentPotato:IndexerTorrentPotato":
                return new IndexerTorrentPotato(name, <any>undefined, { urn })
            case "whisparr:Indexers/indexerTorrentRss:IndexerTorrentRss":
                return new IndexerTorrentRss(name, <any>undefined, { urn })
            case "whisparr:Indexers/indexerTorznab:IndexerTorznab":
                return new IndexerTorznab(name, <any>undefined, { urn })
            case "whisparr:Indexers/restriction:Restriction":
                return new Restriction(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("whisparr", "Indexers/indexer", _module)
pulumi.runtime.registerResourceModule("whisparr", "Indexers/indexerConfig", _module)
pulumi.runtime.registerResourceModule("whisparr", "Indexers/indexerFilelist", _module)
pulumi.runtime.registerResourceModule("whisparr", "Indexers/indexerHdbits", _module)
pulumi.runtime.registerResourceModule("whisparr", "Indexers/indexerIptorrents", _module)
pulumi.runtime.registerResourceModule("whisparr", "Indexers/indexerNewznab", _module)
pulumi.runtime.registerResourceModule("whisparr", "Indexers/indexerNyaa", _module)
pulumi.runtime.registerResourceModule("whisparr", "Indexers/indexerOmgwtfnzbs", _module)
pulumi.runtime.registerResourceModule("whisparr", "Indexers/indexerRarbg", _module)
pulumi.runtime.registerResourceModule("whisparr", "Indexers/indexerTorrentPotato", _module)
pulumi.runtime.registerResourceModule("whisparr", "Indexers/indexerTorrentRss", _module)
pulumi.runtime.registerResourceModule("whisparr", "Indexers/indexerTorznab", _module)
pulumi.runtime.registerResourceModule("whisparr", "Indexers/restriction", _module)
